version: "3.8"

services:
  comfyui:
    image: isaactut/runpod-worker-comfy:dev-sdxl-latest2.3
    container_name: runpod-comfyui-worker
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - SERVE_API_LOCALLY=true
      # - API_HOST=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allows container to access host machine
    ports:
      - "8000:8000"
      - "8188:8188"
    runtime: nvidia
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume
      
    # command: >
    #   bash -c "
    #   mkdir -p /comfyui/output &&
    #   chmod -R 777 /comfyui/output &&
    #   python3 main.py --listen 0.0.0.0 --port 8188 --output-directory /comfyui/output"
