# fly.toml app configuration file generated for modal-builder-falling-frog-5113 on 2024-10-22T11:06:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'modal-builder-falling-frog-5113'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
